---
title: "functions"
author: "Grayson White"
date: "6/17/2020"
output: html_document
---

# Shawn lecture

```{r}
nums <- c(-3, 4, 5, -2)
nums_pos <- abs(nums)
print(nums_pos)

test <- 1/3 == 1/3
print(test)

num1 <- 1/3
num2 <- (1/3) * (1/3) / (1/3)

num1 == num2


# cause rounding error
num1 <- 0.2
num2 <- 0.2 * 0.2 / 0.2

num1 == num2

# rather: check to see if they are "close"
epsilon <- 0.0000001
test <- abs(num1 - num2) < epsilon
test
```

## functions

```{r}
num1 <- 0.2
num2 <- 0.2 * 0.2 / 0.2

equalish <- function(a, b, epsilon = 0.0000001) {
  result <- abs(a - b) < epsilon
  return(result)
}

equalish(num1,num2)

x <- c(4,2)
y <- c(4.000000001, 6)

t <- equalish(x,y)
t

test <- `+`(4,5)
test

# note: functions are "first class", ie, they are data just like any other data. 

print(`+`)
# this means the + operator is written in C, not R.


# defining variables inside a fxn does not add it to the global env., they die when the fxn ends. 
# fxns have access to variables in your global env. 

# ADVICE FOR FXNS
# 1) only use vars that are passed as parameters (which also local) and those defined within the fxn. 
# 2) document fxns -- with some comments, maybe right above the defn of the fxn 
# 3) fxns should be "not too long"

# anonymous fxn
(function(a, b) {
  a ^ b
})(4,5)
```

## lists

```{r}
sample <- list(c(2, 4, 5), c(1, 2, 3, 5), c(1, 9, 5, 6, 2))
sample

sample[[2]]

medians <- list(median(sample[[1]]),
                median(sample[[2]]),
                median(sample[[3]]))
medians

medians <- lapply(sample, median)
# lapply: first arg is a list, second is fxn that applies to each element on the list

medians

answer <- lapply(sample, function(vec_el){
  return(max(vec_el) - min(vec_el))
})

answer
```

functions in R are "pass by value" (ie "pass by copy")

```{r}
equalish <- function(a, b, epsilon = 0.0000001) {
  result <- abs(a - b) < epsilon
  return(result)
}

x <- c(4,2)
y <- c(4.000000001, 6)

equalish(x,y)
```

pyhton is "pass by reference"

`lapply()` is very easy to parallelize. 

... in R:

```{r}
my.read.table <- function(filename, header = TRUE, ...) {
  ans <- read.table(filename, header = TRUE, ...)
  return(ans)
}

# the ... allows you to use all the parameters for `read.table` in `my.read.table`
```


